"use client";
import {useEffect,useMemo,useState} from "react";
type Invoice={id:string;invoiceNumber:string;invoiceDate?:string;currency:string;supplierName?:string;totalAmount:number;extractionConfidence?:number;status:string};
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8080";
export default function Home(){const[invoices,setInvoices]=useState<Invoice[]>([]);const[file,setFile]=useState<File|null>(null);const[uploading,setUploading]=useState(false);const[error,setError]=useState("");
async function loadInvoices(){const r=await fetch(`${API}/api/v1/invoices`,{cache:"no-store"});if(!r.ok)throw new Error("Could not load invoices");setInvoices(await r.json())}
useEffect(()=>{loadInvoices().catch(e=>setError(e.message))},[]);
async function upload(){if(!file)return;setUploading(true);setError("");try{const f=new FormData();f.append("file",file);const r=await fetch(`${API}/api/v1/invoices`,{method:"POST",body:f});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.message??"Upload failed")}setFile(null);await loadInvoices()}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setUploading(false)}}
const total=useMemo(()=>invoices.reduce((s,i)=>s+Number(i.totalAmount||0),0),[invoices]);
return <main className="page"><header className="header"><div><div className="brand">AI Invoice Gateway</div><div className="muted">AI-powered invoice processing</div></div><span className="badge">Phase 1 MVP</span></header><section className="cards"><div className="card"><div className="muted">Invoices</div><div className="metric">{invoices.length}</div></div><div className="card"><div className="muted">Invoice value</div><div className="metric">₹{total.toLocaleString("en-IN")}</div></div><div className="card"><div className="muted">Needs review</div><div className="metric">{invoices.filter(i=>i.status==="REVIEW_REQUIRED").length}</div></div></section><section className="upload"><h2>Upload invoice</h2><p className="muted">PDF, PNG or JPG — demo extraction is enabled until the AI provider is connected.</p><input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]??null)}/><div><button className="btn" disabled={!file||uploading} onClick={upload}>{uploading?"Processing…":"Upload & Extract"}</button></div>{error&&<div className="error">{error}</div>}</section><section><h2>Recent invoices</h2><table className="table"><thead><tr><th>Invoice</th><th>Supplier</th><th>Date</th><th>Total</th><th>Confidence</th><th>Status</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td>{i.invoiceNumber}</td><td>{i.supplierName??"-"}</td><td>{i.invoiceDate??"-"}</td><td>₹{Number(i.totalAmount).toLocaleString("en-IN")}</td><td>{i.extractionConfidence??"-"}%</td><td><span className="badge">{i.status}</span></td></tr>)}{invoices.length===0&&<tr><td colSpan={6} className="muted">No invoices yet.</td></tr>}</tbody></table></section></main>}